services:
  - type: static_site
    name: kryptonix-technologies
    autoDeploy: true
    buildCommand: npm ci && npm run build
    staticPublishPath: out
    envVars:
      - key: NODE_VERSION
        value: 22
