export const projectFilters = [
  "All",
  "Software Development",
  "Web Development",
  "E-commerce",
  "Business Systems",
  "Cloud Services",
  "Digital Transformation",
];

export const portfolioProjects = [
  {
    slug: "vortexus-industrial-excellence",
    title: "Vortexus Industrial Excellence",
    category: "Web Development",

    description:
      "A professional website for a Nairobi-based supplier of water treatment, swimming pool, and solar equipment, with product presentation and enquiry functionality.",

    client: "Vortexus Industrial Excellence",
    industry: "Water Treatment, Swimming Pool & Solar Equipment Supply",
    location: "Nairobi, Kenya",

    liveUrl: "https://vortexusindustrial.com/",

    services: [
      "Business Website Development",
      "Web Development",
      "Lead Generation",
    ],

    problem:
      "The business needed a professional digital presence that could clearly present its products and give potential customers a structured way to make enquiries.",

    approach:
      "Kryptonix structured the website around the company's products, services, brand presentation, and customer enquiry journey.",

    solution:
      "A responsive business website was delivered with product presentation, enquiry functionality, responsive layouts, and supporting digital integrations.",

    technologies: [
      "React.js",
      "Email SMTP",
      "Google Maps",
      "Responsive Design",
      "Chatbot",
      "cPanel",
      "TensorFlow",
    ],

    duration: "1 month",

    image: "/corporate-website.webp",

    evidence: {
      status: "Project delivered; performance evidence pending",

      details:
        "The available project information confirms delivery of a responsive business website aligned with the client's products, services, brand, and enquiry workflow. Verified website traffic, page-performance, conversion, and lead-volume data have not been provided.",

      screenshots: [],
    },

    measurableResults: {
      status: "Not yet verified",
      results: [],
    },

    testimonial: {
      status: "Not yet approved for publication",
      quote: null,
      author: null,
      jobTitle: null,
    },

    permissionToPublish: true,
    approvedForPublicUse: true,
  },

  {
    slug: "norwa-waters",
    title: "Norwa Waters",
    category: "Web Development",

    description:
      "A professional website presenting water treatment, borehole, pumping, and solar solutions, with project information and a structured enquiry journey.",

    client: "Norwa Waters",
    industry: "Water Treatment, Borehole, Pumping & Solar Solutions",
    location: "Kenya / Africa",

    liveUrl: "https://norwawater.com/",

    services: [
      "Business Website Development",
      "Web Development",
      "Lead Generation",
    ],

    problem:
      "The business needed a structured online platform for presenting its water treatment, borehole, pumping, solar solutions, and project information to potential customers.",

    approach:
      "Kryptonix organised the company's services and project information into a clearer digital experience designed to support customer discovery and enquiries.",

    solution:
      "A responsive business website was delivered with service presentation, project information, enquiry functionality, and supporting digital integrations.",

    technologies: [
      "Python",
      "React",
      "Tailwind CSS",
      "Web3Forms",
      "SMTP",
      "Chatbot",
    ],

    duration: "3 weeks",

    image: "/norwa.png",

    evidence: {
      status:
        "Client-reported business figures available; Kryptonix performance metrics pending",

      details:
        "The available project information includes company-reported figures of 120+ completed projects, 45+ project partners, 25,000+ households served, 22M+ litres treated daily, and operations across 12 counties. These figures describe Norwa Waters' reported business activity and are not presented as results generated by the Kryptonix website.",

      screenshots: [],
    },

    measurableResults: {
      status: "Not yet verified",
      results: [],
    },

    testimonial: {
      status: "approved",
      quote: "the work was exxelent",
      author: null,
      jobTitle: null,
    },

    permissionToPublish: true,
    approvedForPublicUse: true,
  },

  {
    slug: "volem-water",
    title: "Volem Water Ltd",
    category: "Web Development",

    description:
      "A professional website for an engineering-led water and wastewater treatment company serving industrial, commercial, institutional, and municipal clients.",

    client: "Volem Water Ltd",
    industry: "Industrial & Municipal Water/Wastewater Treatment",
    location: "Kenya",

    liveUrl: "https://www.volemwater.com/",

    services: [
      "Business Website Development",
      "Web Development",
      "Digital Solutions",
    ],

    problem:
      "The business needed a professional digital platform for communicating its engineering, water treatment, maintenance, monitoring, and consultancy services to different customer groups.",

    approach:
      "Kryptonix organised the company's services and technical offering into a structured, responsive digital experience.",

    solution:
      "A responsive business website was delivered to present the company's engineering and water-treatment services in a clearer and more accessible format.",

    technologies: [
      "Vue.js",
      "Iconify",
      "Web3Forms",
      "Blogify",
      "Dialogflow",
      "Chatbot",
      "OpenRouter",
      "AI Integrations",
    ],

    duration: "1.5 months",

    image: "/volem.png",

    evidence: {
      status: "Project delivered; performance evidence pending",

      details:
        "The available project information confirms delivery of a responsive website presenting engineering, treatment, maintenance, monitoring, and consultancy services. Verified traffic, performance, conversion, and lead-generation metrics have not yet been provided.",

      screenshots: [],
    },

    measurableResults: {
      status: "Not yet verified",
      results: [],
    },

    testimonial: {
      status: "Not yet approved for publication",
      quote: null,
      author: null,
      jobTitle: null,
    },

    permissionToPublish: true,
    approvedForPublicUse: true,
  },

  {
    slug: "norwa-africa",
    title: "Norwa Africa",
    category: "Digital Transformation",

    description:
      "A website presenting water treatment, water pumping, and solar pumping solutions for customers across the African market.",

    client: "Norwa Africa",
    industry: "Water Treatment & Pumping Solutions",
    location: "Africa",

    liveUrl: null,

    services: [
      "Business Website Development",
      "Digital Transformation",
      "Web Development",
    ],

    problem:
      "The available information indicates a need for a digital platform to present water treatment, pumping, and solar pumping solutions to an African market.",

    approach:
      "The available project information supports a website-focused approach for presenting the company's solutions and market offering.",

    solution:
      "A website was developed to present the company's water treatment, water pumping, and solar pumping solutions.",

    technologies: [],

    duration: "To be confirmed",

    image: "/nelda.png",

    evidence: {
      status: "Project information available; public-use approval pending",

      details:
        "The available information includes company-reported business impact figures. These figures have not been independently verified as Kryptonix project results.",

      screenshots: [],
    },

    measurableResults: {
      status: "Not verified",
      results: [],
    },

    testimonial: {
      status: "Pending client approval",
      quote: null,
      author: null,
      jobTitle: null,
    },

    permissionToPublish: false,
    approvedForPublicUse: false,
  },

  {
    slug: "reesolmart",
    title: "Reesolmart",
    category: "E-commerce",

    description:
      "An industrial e-commerce storefront serving the water treatment and borehole equipment sector, supporting product discovery and supplier marketplace workflows.",

    client: "Reesolmart",
    industry: "Industrial E-commerce / Supplier Marketplace",
    location: "Kenya",

    liveUrl: "https://www.reesolmart.com/",

    services: [
      "E-commerce Development",
      "Business Systems",
      "Web Development",
    ],

    problem:
      "The business needed an online platform supporting product discovery, supplier workflows, administration, dashboards, and digital payments for an industrial marketplace.",

    approach:
      "Kryptonix combined e-commerce functionality with supplier, administration, dashboard, and payment capabilities to support the marketplace workflow.",

    solution:
      "An industrial e-commerce platform was delivered with product and supplier functionality, administrative systems, dashboards, and payment integrations.",

    technologies: [
      "Django",
      "Python",
      "React",
      "SMTP",
      "Dashboards",
      "Admin Systems",
      "M-Pesa API",
      "PayPal",
    ],

    duration: "3 months",

    image: "/reesolmart.png",

    evidence: {
      status:
        "Project functionality documented; performance metrics pending",

      details:
        "The available information confirms e-commerce, supplier, dashboard, administration, and payment functionality. Verified transaction volume, traffic, conversion rate, revenue, or lead-generation results have not been provided.",

      screenshots: [],
    },

    measurableResults: {
      status: "Not yet verified",
      results: [],
    },

    testimonial: {
      status: "Not yet approved for publication",
      quote: null,
      author: null,
      jobTitle: null,
    },

    permissionToPublish: true,
    approvedForPublicUse: true,
  },

  {
    slug: "nelda-engineering-solutions",
    title: "Nelda Engineering Solutions Ltd",
    category: "Web Development",

    description:
      "A professional website for an engineering solutions company, presenting its services and digital contact channels.",

    client: "Nelda Engineering Solutions Ltd",
    industry: "Engineering Solutions",
    location: "Kenya",

    liveUrl: null,

    services: [
      "Business Website Development",
      "Web Development",
      "Digital Solutions",
    ],

    problem:
      "The business needed a professional online presence for presenting its engineering services and providing customers with digital contact channels.",

    approach:
      "Kryptonix structured the company's service information and contact journey into a responsive business website.",

    solution:
      "A professional responsive website was delivered with service presentation and digital contact functionality.",

    technologies: [
      "Vue.js",
      "Iconify",
      "Web3Forms",
      "Blogify",
      "Dialogflow",
      "Chatbot",
      "OpenRouter",
      "AI Integrations",
    ],

    duration: "1 month",

    image: "/nelda.png",

    evidence: {
      status: "Project delivered; performance evidence pending",

      details:
        "The available project information confirms delivery of a professional business website. Verified traffic, performance, conversion, and lead-generation metrics have not yet been provided.",

      screenshots: [],
    },

    measurableResults: {
      status: "Not yet verified",
      results: [],
    },

    testimonial: {
      status: "Not yet approved for publication",
      quote: null,
      author: null,
      jobTitle: null,
    },

    permissionToPublish: true,
    approvedForPublicUse: true,
  },
];